# Azure Environment
variable "projectPrefix" {}
variable "location" {}
variable "region" {}
variable "adminPassword" {}
variable "namespace" {}
variable "cidr" {}
variable "subnets" {}
variable "tags" {}
variable "f5_t1_ext" {}
