# Volterra Environment
variable "projectPrefix" {}
variable "location" {}
variable "region" {}
variable "sshPublicKey" {}
variable "sshPublicKeyPath" {}
variable "existing_vnet" {}
variable "bigip_external" {}
variable "delegated_domain" {}
variable "namespace" {}
variable "api_p12_file" {}
variable "name" {}
variable "url" {}
variable "azure_client_id" {}
variable "azure_client_secret" {}
variable "azure_tenant_id" {}
variable "azure_subscription_id" {}
variable "resource_group_name" {}
variable "azure_resource_group_name" {}
variable "volterra_tf_action" {}
variable "subnet_internal" {}
variable "subnet_external" {}
variable "subnet_inspec_ext" {}
variable "gateway_type" {}
variable "fleet_label" {}
variable "cidr" {}
variable "azure_subnets" {}
variable "tags" {}
